// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GameMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GameMessage.proto</summary>
public static partial class GameMessageReflection {

  #region Descriptor
  /// <summary>File descriptor for GameMessage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GameMessageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFHYW1lTWVzc2FnZS5wcm90byJUCgtNb3ZlTWVzc2FnZRINCgVTY2VuZRgB",
          "IAIoAxIOCgZFbnRpdHkYAiACKAMSEgoKRGlyZWN0aW9uWBgDIAIoAhISCgpE",
          "aXJlY3Rpb25ZGAQgAigC"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MoveMessage), global::MoveMessage.Parser, new[]{ "Scene", "Entity", "DirectionX", "DirectionY" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class MoveMessage : pb::IMessage<MoveMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<MoveMessage> _parser = new pb::MessageParser<MoveMessage>(() => new MoveMessage());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<MoveMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GameMessageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MoveMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MoveMessage(MoveMessage other) : this() {
    _hasBits0 = other._hasBits0;
    scene_ = other.scene_;
    entity_ = other.entity_;
    directionX_ = other.directionX_;
    directionY_ = other.directionY_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public MoveMessage Clone() {
    return new MoveMessage(this);
  }

  /// <summary>Field number for the "Scene" field.</summary>
  public const int SceneFieldNumber = 1;
  private readonly static long SceneDefaultValue = 0L;

  private long scene_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Scene {
    get { if ((_hasBits0 & 1) != 0) { return scene_; } else { return SceneDefaultValue; } }
    set {
      _hasBits0 |= 1;
      scene_ = value;
    }
  }
  /// <summary>Gets whether the "Scene" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasScene {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "Scene" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearScene() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "Entity" field.</summary>
  public const int EntityFieldNumber = 2;
  private readonly static long EntityDefaultValue = 0L;

  private long entity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Entity {
    get { if ((_hasBits0 & 2) != 0) { return entity_; } else { return EntityDefaultValue; } }
    set {
      _hasBits0 |= 2;
      entity_ = value;
    }
  }
  /// <summary>Gets whether the "Entity" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasEntity {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "Entity" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearEntity() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "DirectionX" field.</summary>
  public const int DirectionXFieldNumber = 3;
  private readonly static float DirectionXDefaultValue = 0F;

  private float directionX_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float DirectionX {
    get { if ((_hasBits0 & 4) != 0) { return directionX_; } else { return DirectionXDefaultValue; } }
    set {
      _hasBits0 |= 4;
      directionX_ = value;
    }
  }
  /// <summary>Gets whether the "DirectionX" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDirectionX {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "DirectionX" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDirectionX() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "DirectionY" field.</summary>
  public const int DirectionYFieldNumber = 4;
  private readonly static float DirectionYDefaultValue = 0F;

  private float directionY_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float DirectionY {
    get { if ((_hasBits0 & 8) != 0) { return directionY_; } else { return DirectionYDefaultValue; } }
    set {
      _hasBits0 |= 8;
      directionY_ = value;
    }
  }
  /// <summary>Gets whether the "DirectionY" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasDirectionY {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "DirectionY" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearDirectionY() {
    _hasBits0 &= ~8;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as MoveMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(MoveMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Scene != other.Scene) return false;
    if (Entity != other.Entity) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DirectionX, other.DirectionX)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DirectionY, other.DirectionY)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasScene) hash ^= Scene.GetHashCode();
    if (HasEntity) hash ^= Entity.GetHashCode();
    if (HasDirectionX) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DirectionX);
    if (HasDirectionY) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DirectionY);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasScene) {
      output.WriteRawTag(8);
      output.WriteInt64(Scene);
    }
    if (HasEntity) {
      output.WriteRawTag(16);
      output.WriteInt64(Entity);
    }
    if (HasDirectionX) {
      output.WriteRawTag(29);
      output.WriteFloat(DirectionX);
    }
    if (HasDirectionY) {
      output.WriteRawTag(37);
      output.WriteFloat(DirectionY);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasScene) {
      output.WriteRawTag(8);
      output.WriteInt64(Scene);
    }
    if (HasEntity) {
      output.WriteRawTag(16);
      output.WriteInt64(Entity);
    }
    if (HasDirectionX) {
      output.WriteRawTag(29);
      output.WriteFloat(DirectionX);
    }
    if (HasDirectionY) {
      output.WriteRawTag(37);
      output.WriteFloat(DirectionY);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasScene) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Scene);
    }
    if (HasEntity) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Entity);
    }
    if (HasDirectionX) {
      size += 1 + 4;
    }
    if (HasDirectionY) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(MoveMessage other) {
    if (other == null) {
      return;
    }
    if (other.HasScene) {
      Scene = other.Scene;
    }
    if (other.HasEntity) {
      Entity = other.Entity;
    }
    if (other.HasDirectionX) {
      DirectionX = other.DirectionX;
    }
    if (other.HasDirectionY) {
      DirectionY = other.DirectionY;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Scene = input.ReadInt64();
          break;
        }
        case 16: {
          Entity = input.ReadInt64();
          break;
        }
        case 29: {
          DirectionX = input.ReadFloat();
          break;
        }
        case 37: {
          DirectionY = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Scene = input.ReadInt64();
          break;
        }
        case 16: {
          Entity = input.ReadInt64();
          break;
        }
        case 29: {
          DirectionX = input.ReadFloat();
          break;
        }
        case 37: {
          DirectionY = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
